name: docker - build and publish


on:
  push:
    branches:
      - main

  
jobs:
  build-publish-jirabot:
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: "submodule checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build jira_bot"
        run: |
          docker compose build -t ghcr.io/bmln/jira_bot jira_bot

      - name: "Publish jira_bot"
        run: |
          docker push ghcr.io/bmln/jira_bot